import numpy as np
import timml
import dill
"""
tim_editor is a tool that allows for significantly faster probabilistic analyses using timflow steady state models.
The way this works is by preserving the majority of the large tim model matrix generated by model.solve, for large models the generation of this matrix
takes up a large majority of the processing time. Whereas a probabilistic analysis that directly uses tim would throw away this entire matrix for any parameter change,
tim_editor only replaces part of the matrix and leaves the rest intact. During testing in large sample sizes this resulted in a ~300 times speedup compared to directly running tim.

tim_editor is not a magic solution however, and has certain specific limitations:
    - As of right now, only the river resistance can be altered, some other parameters might be usable as well but there are parameters which simply impact
    the matrix in too many ways for this method to be feasible
    - Rivers must not cross inhomogeneity borders
    - tim_editor needs to be "trained" which involves running the model x times where x is the amount of editable rivers
"""

def build_small(element, res_new):
    """
    Builds a single-element model containing a River with the desired resistance
    Inputs are the element from the original model that is being modified, and the desired resistance
    This function is only called by inject_res
    """
    timml_model = timml.ModelMaq(
        kaq=element["kaq"],
        z=element["z"],
        c=element["c"],
        topboundary='semi',
        npor=[None, None, None, None],
        hstar=element["hstar"],
    )
    river =  timml.RiverString(
        model=timml_model,
        xy=element["xy"],
        hls=element["hls"],
        res=res_new,
        wh=element["wh"],
        order=element["order"],
        layers=element["layers"],
        label=element["label"],
    )
    a,b=timml_model.solve(printmat=True, silent=True)
    return a, b, timml_model

def inject_res(editloc, res_new, mat):
    """
    'injects' a desired resistance into the timflow model matrix using a single-element model
    Inputs are the editloc (edit location) tuple generated by generate_editloc, the desired resistance (scalar float) and the matrix to be modified (2D numpy array)
    The matrix is modified in place and returned

    The way this works is that the editloc tuple contains the location of the element's small matrix in the model's big matrix, 
    in the case of an order 4 line element this is a 5x5 matrix. This matrix is then re-generated using build_small with the desired resistance and 'injected'
    into the model.
    """
    a3, b3, model_small = build_small(editloc[0], res_new)
    mat[editloc[1][0]:editloc[1][0]+a3.shape[0], editloc[1][1]:editloc[1][1]+a3.shape[0]]=a3
    return mat

def generate_editloc(mat_base_model, base_model, mat_changed_model, element_name):
    """
    Generates an "editloc" (edit location) tuple that holds the element that is to be edited and its location in the model matrix,
    This is done using the matrix of the original model, and the matrix of a copy of the original model with 1 resistance value altered.

    Inputs are the matrix of the base model, the base model itself, the matrix of the changed model and the name of the element that was altered.
    It returns the editloc tuple

    The way this works is that it finds out where the difference between the original model and the altered model is non-zero
    When only a single river's resistance is being altered this will be a square with side order+1
    It then stores the top left edge of this location, together with some information about the element which is needed for build_small
    """
    element=base_model.elementdict[element_name]
    element_to_edit={
        "kaq":element.aq[0].kaq,
        "z":element.aq[0].z,
        "c":element.aq[0].c,
        "hstar":element.aq[0].hstar,
        "xy":element.xy,
        "hls":element.hls,
        "wh":element.wh,
        "order":element.order,
        "layers":element.layers,
        "label":element.label
    }
    location= np.argwhere(mat_base_model-mat_changed_model)[0]
    return (element_to_edit,location)

def solve_from(mat, rhs, model):
    """
    Solves a tim model based on its matrix and rhs, in essence this is simply the latter bit of model.solve()
    This code comes from timflow source code, timflow's license therefore applies.
    """
    sol = np.linalg.solve(mat, rhs)
    icount = 0
    for e in model.elementlist:
        if e.nunknowns > 0:
            e.setparams(sol[icount : icount + e.nunknowns])
            icount += e.nunknowns

def surrogate_model(editlocs, mat_base, model_base, res, rhs):
    """
    Using a list of editlocs and resistances, this 'injects' the small matrices into a base big matrix to generate model matrices with the desired resistances
    After generating the new big matrix it uses solve_from in order to get the results, which it puts into model_base
    The properties of model_base's elements do not exactly match those in the injected matrix, but it does not complain and the results work as expected

    The inputs are the editlocs tuple, the matrix to inject onto, a model which matches the base matrix, the tuple of input resistances and the rhs of the base model
    """
    for i in range(len(res)):
        mat_base=inject_res(editlocs[i], res[i],mat_base)
    solve_from(mat_base, rhs, model_base)
    return model_base

def generate_editlocs(mat_base, model_base,res_base, wrapped_model):
    """
    Generates a list of editlocs for river elements named 'editableRiver', to be used in the other tim_editor functions
    The inputs are the matrix, model and resistance tuple of the base model, and the function wrapped_model, which is
    the relevant tim model wrapped into a function that takes a tuple of resistances as argument, and returns the results of
    tim_model.solve(printmat=True) in addition to the model object
    """
    editlocs=[]
    for i in range(len(res_base)):
        res=list(res_base)
        res[i]=70
        mat, rhs, timml_model= wrapped_model(res)
        editlocs.append(generate_editloc(mat_base, model_base, mat,"editableRiver"+str(i)))
    return editlocs

def generate_inputs(resTup, wrapped_model):
    """
    Stores editlocs as a pickle so they only need to be calculated once per model in order to reach the practical goal of
    saving time.
    Additionally saves the matrix and rhs of the base model
    """
    mat_base, rhs_base, timml_model_base= wrapped_model(resTup)
    with open("model","wb") as f:
        dill.dump([mat_base,rhs_base],f)
    editlocs=generate_editlocs(mat_base, timml_model_base, resTup, wrapped_model)
    with open("editlocs", "wb") as f:
       dill.dump(editlocs, f)

def load_inputs(resTup, modelfunc):
    """
    Loads editlocs, mat_base and rhs_base, and creates an initialised (but not solved) model instance
    """
    with open("model","rb") as f:
        matrices=dill.load(f)
    mat_base = matrices[0]
    rhs_base = matrices[1]
    timml_model_base = modelfunc(*resTup)
    timml_model_base.initialize()
    with open("editlocs", "rb") as f:
        editlocs=dill.load(f)
    return mat_base, rhs_base, timml_model_base, editlocs
